### ISSUE TITLE
Add ability to configure alarms for INT pin

### ISSUE THREAD

**Issue by wildestpixel** [adafruit/Adafruit_CircuitPython_LC709203F#12]
I see this described as follows : 

`INT - Interrupt signal out, you can set this up to pull low when the voltage or percentage drops below a threshold. Pulled up to VIN with a 10K resistor`

Does this automatically trigger when IC senses battery too low, or is this programatically triggered ?

EDIT - 

From Datasheet appears to be be written at 1 of 2 registers, but doesn't appear as though library enables this

**Comment by ladyada** [comment]
hi this isnt a bug report, tech support is handled in the forums. thanks :)

**Comment by caternuson** [comment]
Reopening and changing title to better reflect issue. This library is missing functions to set registers 0x13 and 0x14 which control the INT pint behavior.

Arduino lib implementation for ref:
https://github.com/adafruit/Adafruit_LC709203F/blob/78acd68fd6915cd8646ed89fb02cac9351586174/Adafruit_LC709203F.cpp#L172-L190

**Comment by jrrickerson** [comment]
I'm starting to look at this during the PyCon US 2023 sprints.
