### ISSUE TITLE
Fixed Charged Voltage

### ISSUE THREAD

**Issue by HB-Git** [adafruit/Adafruit_CircuitPython_LC709203F#6]
Hi,
I'm using the "Adafruit Universal USB / DC / Solar Lithium Ion/Polymer charger - bq24074" to charge my 2000mAh Lipo,in my case when connected to a USB port it charges 'only' up to 4.188V (measured with a multimeter at the lipo output). The LC709203F in line in the circuit at this moment shows 3-4mV more... so 4.192V. Still the SOC is 84.4% even after waiting for more than 3 hours now.. If I could lower the fixed charged voltage to say 4.19 (or even a bit lower), I could tweak the SOC to sync to 100% earlier.
I'm not sure what the Arduino code 'Pack_size' does (as you can set this), but I can seem to find to change this parameter in CircuitPython.
BR, Bob

**Comment by ladyada** [comment]
v1.0.1 has a fix for the charge voltage - please upgrade to latest version in this repo. thanx!
