### ISSUE TITLE
Package and Class name don't match

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/Adafruit_CircuitPython_LC709203F#7]
Is there a reason that the class name isn't the same as the package name, or is it just a typo?
They are the same in the Arduino version.

ex: from adafruit_lc709203f import LC709023F 

Happy to do a PR if its a bug.
This guide would also need updating:
https://learn.adafruit.com/adafruit-lc709203f-lipo-lipoly-battery-monitor

**Comment by ladyada** [comment]
oi thats a typo... too many numbers!
yeah could you submit a pr? we'll fix the guide :)
